// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm4QEi6lRyi1UbJSDS4zT_Je76IdIvrOg',
    appId: '1:630318929273:web:08da2f20ac2f8416660ba8',
    messagingSenderId: '630318929273',
    projectId: 'nguyenbao-fd5ff',
    authDomain: 'nguyenbao-fd5ff.firebaseapp.com',
    storageBucket: 'nguyenbao-fd5ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-Kr6q59XLtwFkuns7CSBNMUMG77lzN8',
    appId: '1:630318929273:android:62258804c8b95e6b660ba8',
    messagingSenderId: '630318929273',
    projectId: 'nguyenbao-fd5ff',
    storageBucket: 'nguyenbao-fd5ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVyYmn-jSXWONyP4n0RRAQNvLukupYpo',
    appId: '1:630318929273:ios:6c392dc6fd344264660ba8',
    messagingSenderId: '630318929273',
    projectId: 'nguyenbao-fd5ff',
    storageBucket: 'nguyenbao-fd5ff.firebasestorage.app',
    iosBundleId: 'com.example.appthoitiet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm4QEi6lRyi1UbJSDS4zT_Je76IdIvrOg',
    appId: '1:630318929273:web:70644c47adc80132660ba8',
    messagingSenderId: '630318929273',
    projectId: 'nguyenbao-fd5ff',
    authDomain: 'nguyenbao-fd5ff.firebaseapp.com',
    storageBucket: 'nguyenbao-fd5ff.firebasestorage.app',
  );
}
